spring.application.name=blog-api

spring.datasource.url=jdbc:postgresql://localhost:5432/blog_db
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true

server.port=8080